### ISSUE TITLE
Auto-generate docs on build

### ISSUE THREAD

**Issue by rmil** [ystv/web-api#8]
We can then ensure we are always on the latest version of the docs. Also, we can then provide feedback if it's a successful doc compile for each commit.

Need to run `swag init -g routes/router.go` and the docs will generate. This does require `swag` as a dependency however.

**Comment by rmil** [comment]
Did a little nosey into this, you'll need to update the Dockerfile to just include the go get of the binary and just execute that command. The issue is that it's having issues generating docs when the model features an external model inside of itself (a lot of models benefit from the null package, so this makes it difficult to implement).

**Comment by rmil** [comment]
Only seem to be having issues when I'm not generating in my normal dev environment, so in docker it has issues whilst outside it doesn't

**Comment by cs-499243** [comment]
It's not strictly been coded to auto generate these but a working process of generating docs is in the install procedure

**Comment by rmil** [comment]
Fixed in #15
